import type { TrainingConfig } from './types';

export const defaultTrainingConfig: TrainingConfig = {
  epochs: 500,
  batchSize: 128,
  lr: 0.0002,
  warmupEpochs: 3,
  valRatio: 0.1,
  inputSize: 32,
  arch: 'tinycnn',
  inputMode: 'raw3',
  intensityNorm: 'robust',
  norm: 'group',
  pooling: 'avgmax',
  balancedSampler: 0,
  ngHardAugRepeat: 1,
  guardNgTrainRepeat: 2,
  earlyStop: 0,
  selectionMode: 'fp-under-fn-cap',
  maxValFn: 2,
  maxGuardFn: 15,
  posWeight: 'auto',
  loss: 'bce',
  minThreshold: 0.05,
  thresholdMargin: 0.03,
  maxThreshold: 0.75,
  seed: 42,
  device: 'cpu',
  numWorkers: 4,
  amp: 0,
  channelsLast: 0,
  prefetchFactor: 4,
  evalEvery: 1,
  guardEvalEvery: 5,
  cudnnBenchmark: 0
};
